### ISSUE TITLE
Use Release trigger for official NuGet release

### ISSUE THREAD

**Issue by tig** [migueldeicaza/gui.cs#875]
GitHub has a wonderful concept of releases, which is an extra layer on top of git tags and which provide a nice UI to create, manage and view a release.

We should use GitHub releases as a formal and conscious step to create, document and publish a NuGet package.

Add the release option as an additional CI trigger:

```yaml
on:
  push:
  pull_request:
  release:
    types:
      - published
```

In order to kick off a deployment for a GitHub Release create a job called `deploy`:

```yaml
deploy:
  needs: build
  if: github.event_name == 'release'
  runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Create Release NuGet package
      run: |
        ...
        ...
        dotnet pack -v normal -c Release --include-symbols --include-source -p:PackageVersion=$VERSION -o nupkg src/$PROJECT_NAME/$PROJECT_NAME.*proj
    - name: Push to GitHub Feed
      run: |
        for f in ./nupkg/*.nupkg
        do
          curl -vX PUT -u "$GITHUB_USER:$GITHUB_TOKEN" -F package=@$f $GITHUB_FEED
        done
    - name: Push to NuGet Feed
      run: dotnet nuget push ./nupkg/*.nupkg --source $NUGET_FEED --skip-duplicate --api-key $NUGET_KEY
```
